/*
  Warnings:

  - You are about to drop the `Property` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropTable
DROP TABLE "Property";

-- CreateTable
CREATE TABLE "DProperty" (
    "ListingId" TEXT NOT NULL,
    "Utilities" JSONB,
    "HMS_SaleOptions" TEXT,
    "PossibleUse" JSONB,
    "GreenEnergyEfficient" JSONB,
    "LotSizeDimensions" TEXT,
    "Zoning" TEXT,
    "RoadSurfaceType" JSONB,
    "VirtualTourURLUnbranded" JSONB,
    "WindowFeatures" JSONB,
    "HMS_Telecom" TEXT,
    "SecurityFeatures" JSONB,
    "AssociationFeeIncludes" JSONB,
    "HMS_InsideCityLimits" TEXT,
    "OwnershipType" TEXT,
    "Appliances" JSONB,
    "RoadResponsibility" JSONB,
    "BuilderModel" TEXT,
    "AssociationAmenities" JSONB,
    "CoListAgentFullName" TEXT,
    "CoListAgentMlsId" TEXT,
    "CoListOfficeName" TEXT,
    "CoListOfficePhone" TEXT,
    "YearBuilt" INTEGER,
    "Flooring" JSONB,
    "Possession" JSONB,
    "AssociationFeeFrequency" TEXT,
    "HMS_WarrantyDescription" TEXT,
    "InteriorFeatures" JSONB,
    "PatioAndPorchFeatures" JSONB,
    "RoomsTotal" INTEGER,
    "HighSchool" TEXT,
    "MiddleOrJuniorSchool" TEXT,
    "ArchitecturalStyle" JSONB,
    "BuilderName" TEXT,
    "ElementarySchool" TEXT,
    "FireplaceFeatures" JSONB,
    "LaundryFeatures" JSONB,
    "LotFeatures" JSONB,
    "PropertyCondition" JSONB,
    "FireplacesTotal" INTEGER,
    "AboveGradeFinishedArea" INTEGER,
    "AboveGradeFinishedAreaUnits" TEXT,
    "BelowGradeFinishedArea" INTEGER,
    "BelowGradeFinishedAreaUnits" TEXT,
    "GarageSpaces" INTEGER,
    "Basement" JSONB,
    "BasementYN" BOOLEAN,
    "BathroomsFull" INTEGER,
    "BathroomsHalf" INTEGER,
    "BedroomsTotal" INTEGER,
    "Cooling" JSONB,
    "CoolingYN" BOOLEAN,
    "FireplaceYN" BOOLEAN,
    "GarageYN" BOOLEAN,
    "HMS_BathroomsTotalDecimal" TEXT,
    "HMS_ExclusionsYN" TEXT,
    "HMS_FloorPlanFeatures" TEXT,
    "Heating" JSONB,
    "LivingArea" INTEGER,
    "Ownership" TEXT,
    "Roof" JSONB,
    "LotSizeArea" DOUBLE PRECISION,
    "LotSizeSquareFeet" DOUBLE PRECISION,
    "ParkingFeatures" JSONB,
    "LotSizeUnits" TEXT,
    "HMS_AgeDescription" TEXT,
    "AssociationFee" INTEGER,
    "HMS_LegalDescription" TEXT,
    "SubAgencyCompensationType" TEXT,
    "HMS_MaintenanceProvidedYN" TEXT,
    "HighSchoolDistrict" TEXT,
    "Sewer" TEXT,
    "SubdivisionName" TEXT,
    "WaterSource" TEXT,
    "Directions" JSONB,
    "StreetNumber" TEXT,
    "HMS_InFloodPlain" TEXT,
    "HMS_TaxTotalAmount" TEXT,
    "PropertySubType" TEXT,
    "odataid" TEXT,
    "BuyerAgencyCompensation" TEXT,
    "BuyerAgencyCompensationType" TEXT,
    "City" TEXT,
    "CountyOrParish" TEXT,
    "InternetAddressDisplayYN" BOOLEAN,
    "InternetEntireListingDisplayYN" BOOLEAN,
    "ListAgentDirectPhone" TEXT,
    "ListAgentFullName" TEXT,
    "ListAgentKey" TEXT,
    "ListAgentMlsId" TEXT,
    "ListOfficeKey" TEXT,
    "ListOfficeMlsId" TEXT,
    "ListOfficeName" TEXT,
    "ListOfficePhone" TEXT,
    "ListPrice" INTEGER,
    "ListingAgreement" TEXT,
    "ListingContractDate" TEXT,
    "ListingKey" TEXT,
    "ListingTerms" JSONB,
    "MLSAreaMajor" TEXT,
    "MlgCanUse" JSONB,
    "MlgCanView" BOOLEAN,
    "MlsStatus" TEXT,
    "ModificationTimestamp" TEXT,
    "OriginatingSystemName" TEXT,
    "ParcelNumber" TEXT,
    "PhotosChangeTimestamp" TEXT,
    "PhotosCount" INTEGER,
    "PostalCode" TEXT,
    "PropertyType" TEXT,
    "PublicRemarks" JSONB,
    "StandardStatus" TEXT,
    "StateOrProvince" TEXT,
    "StreetName" TEXT,
    "StreetSuffix" TEXT,
    "SubAgencyCompensation" TEXT,

    CONSTRAINT "DProperty_pkey" PRIMARY KEY ("ListingId")
);
