export type Property = {
    ListingId: String //Prisma @id
    Utilities: JSON
    HMS_SaleOptions: String
    PossibleUse: JSON
    GreenEnergyEfficient: JSON
    LotSizeDimensions: String
    Zoning: String
    RoadSurfaceType: JSON
    VirtualTourURLUnbranded: JSON
    WindowFeatures: JSON
    HMS_Telecom: String
    SecurityFeatures: JSON
    AssociationFeeIncludes: JSON
    HMS_InsideCityLimits: String
    OwnershipType: String
    Appliances: JSON
    RoadResponsibility: JSON
    BuilderModel: String
    AssociationAmenities: JSON
    CoListAgentFullName: String
    CoListAgentMlsId: String
    CoListOfficeName: String
    CoListOfficePhone: String
    YearBuilt: Number
    Flooring: JSON
    Possession: JSON
    AssociationFeeFrequency: String
    HMS_WarrantyDescription: String
    InteriorFeatures: JSON
    PatioAndPorchFeatures: JSON
    RoomsTotal: Number
    HighSchool: String
    MiddleOrJuniorSchool: String
    ArchitecturalStyle: JSON
    BuilderName: String
    ElementarySchool: String
    FireplaceFeatures: JSON
    LaundryFeatures: JSON
    LotFeatures: JSON
    PropertyCondition: JSON
    FireplacesTotal: Number
    AboveGradeFinishedArea: Number
    AboveGradeFinishedAreaUnits: String
    BelowGradeFinishedArea: Number
    BelowGradeFinishedAreaUnits: String
    GarageSpaces: Number
    Basement: JSON
    BasementYN: Boolean
    BathroomsFull: Number
    BathroomsHalf: Number
    BedroomsTotal: Number
    Cooling: JSON
    CoolingYN: Boolean
    FireplaceYN: Boolean
    GarageYN: Boolean
    HMS_BathroomsTotalDecimal: String
    HMS_ExclusionsYN: String
    HMS_FloorPlanFeatures: String
    Heating: JSON
    LivingArea: Number
    Ownership: String
    Roof: JSON
    LotSizeArea: Number
    LotSizeSquareFeet: Number
    ParkingFeatures: JSON
    LotSizeUnits: String
    HMS_AgeDescription: String
    AssociationFee: Number
    HMS_LegalDescription: String
    SubAgencyCompensationType: String
    HMS_MaintenanceProvidedYN: String //array, grab index 0
    HighSchoolDistrict: String
    Sewer: String //array, grab index 0
    SubdivisionName: String
    WaterSource: String //this comes in as an array, grab index 0
    Directions: String
    StreetNumber: String
    HMS_InFloodPlain: String
    HMS_TaxTotalAmount: String
    PropertySubType: String
    odataid: String
    BuyerAgencyCompensation: String
    BuyerAgencyCompensationType: String
    City: String
    CountyOrParish: String
    InternetAddressDisplayYN: Boolean
    InternetEntireListingDisplayYN: Boolean
    ListAgentDirectPhone: String
    ListAgentFullName: String
    ListAgentKey: String
    ListAgentMlsId: String
    ListOfficeKey: String
    ListOfficeMlsId: String
    ListOfficeName: String
    ListOfficePhone: String
    ListPrice: Number
    ListingAgreement: String
    ListingContractDate: String
    ListingKey: String
    ListingTerms: JSON
    MLSAreaMajor: String
    MlgCanUse: JSON
    MlgCanView: Boolean
    MlsStatus: String
    ModificationTimestamp: String
    OriginatingSystemName: String
    ParcelNumber: String
    PhotosChangeTimestamp: String
    PhotosCount: Number
    PostalCode: String
    PropertyType: String
    PublicRemarks: String
    StandardStatus: String
    StateOrProvince: String
    StreetName: String
    StreetSuffix: String
    SubAgencyCompensation: String

}
